# Generated by Django 3.0.2 on 2020-01-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
