# Generated by Django 3.0.2 on 2020-01-19 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20200119_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='table',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table', to='restaurant.Table'),
        ),
    ]
